spring.application.name=REVIEW-SERVICE

logging.level.org.springframework.security=TRACE

spring.config.import=optional:configserver:http://localhost:8888

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true

spring.cloud.openfeign.httpclient.hc5.enabled=true
spring.cloud.openfeign.httpclient.connection-timeout=5000
spring.cloud.openfeign.httpclient.hc5.connection-request-timeout=5
spring.cloud.openfeign.httpclient.hc5.connection-request-timeout-unit=seconds
spring.cloud.openfeign.httpclient.hc5.socket-timeout=30
spring.cloud.openfeign.httpclient.hc5.socket-timeout-unit=seconds
